Document: mylittledeb
Title: Debian mylittledeb Manual
Author: <insert document author here>
Abstract: This manual describes what mylittledeb is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mylittledeb/mylittledeb.sgml.gz

Format: postscript
Files: /usr/share/doc/mylittledeb/mylittledeb.ps.gz

Format: text
Files: /usr/share/doc/mylittledeb/mylittledeb.text.gz

Format: HTML
Index: /usr/share/doc/mylittledeb/html/index.html
Files: /usr/share/doc/mylittledeb/html/*.html
